emerge mdadm
emerge wavemon
emerge dclfdd
emerge terminator
emerge logrotate
emerge thunderbird
emerge gimp
emerge app-crypt/steghide
emerge net-analyzer/dirsearch
emerge binwalk
emerge net-analyzer/ffuf
emerge net-analyzer/masscan
emerge net-analyzer/testssl
emerge net-analyzer/xsstrike
emerge net-wireless/uhd
emerge net-wireless/airgeddon
emerge net-wireless/eaphammer
emerge suricata
emerge sys-apps/hwinfo
emerge net-im/signal-desktop-bin
emerge dev-python/pip
emerge mpv
emerge libheif
emerge dev-python/jq
emerge app-arch/bzip2
emerge lshw
emerge app-misc/mc
#segfaults emerge net-wireless/btscanner
emerge net-analyzer/testssl
emerge net-mail/swaks
net-analyzer/arp-scan
emerge =dev-lang/python-2*
emerge media-tv/v4l-utils
emerge dev-python/notebook
emerge dev-embedded/sdcc
