emerge mdadm
emerge dclfdd
emerge terminator
emerge logrotate
emerge media-gfx/gimp
emerge media-gfx/geeqie
emerge app-crypt/steghide
emerge app-misc/binwalk
emerge net-analyzer/dirsearch
emerge net-analyzer/ffuf
emerge net-analyzer/masscan
emerge net-analyzer/testssl
emerge net-analyzer/xsstrike
emerge net-analyzer/iftop
emerge net-analyzer/suricata
emerge net-wireless/uhd
emerge net-wireless/airgeddon
emerge net-wireless/wavemon
emerge net-wireless/eaphammer
emerge sys-apps/hwinfo
emerge net-im/signal-desktop-bin
emerge media-video/mpv
emerge media-tv/v4l-utils
emerge libheif
emerge app-arch/bzip2
emerge lshw
emerge app-misc/mc
#segfaults emerge net-wireless/btscanner
emerge net-mail/swaks
net-analyzer/arp-scan
emerge =dev-lang/python-2*
emerge dev-python/pip
emerge dev-python/notebook
emerge dev-python/jq
emerge dev-embedded/sdcc
emerge net-firewall/ipset
emerge net-irc/irssi
emerge dev-python/csvkit
