systemctl enable audit
systemctl start audit
systemctl enable acct
systemctl start acct
systemctl enable ssh
systemctl start ssh
systemctl set-default multi-user.target
systemctl enable sysstat
systemctl start sysstat
systemctl enable haveged
systemctl start haveged
systemctl disable lightdm
systemctl start docker
systemctl enable docker
systemctl enable libvirt-guests
systemctl start libvirt-guests
systemctl enable smartmontools
systemctl start smartmontools
systemctl enable rsyslog
systemctl start rsyslog
